Support Timestamps in where queries
Upstatement/firestore-jest-mock pull request #114
Opened 2021-07-19 16:04 UTC by netdown

# Description

Currently filtering Timestamps does not work at all because they are compared as strings, this pr adds support for comparing with Date objects.

2021-07-23 15:23 UTC, sbatson5 commented
Looks like we have a few failing tests related to querying

2021-07-24 11:06 UTC, netdown commented
@sbatson5 Fixed.

2021-08-06 14:18 UTC, sbatson5 requested changes
The logic here seems sound.  Can we just get a new test case asserting that we can compare a timestamp to a date?

2021-08-12 01:38 UTC, MorenoMdz commented
This one will be very helpful, waiting for the final update here.

2021-08-14 14:21 UTC, sbatson5 approved these changes
Thanks for these tests 🙌

2021-08-14 14:29 UTC, merged